tunnel_servers:
  - label: 터널 서버 1
    host: tunnel_server1
    port: 22
    user: tunnel_user1
  - label: 터널 서버 2
    host: tunnel_server2
    port: 22
    user: tunnel_user2

node:
  name: node1
  host: node1
  port: 22
  user: node_user

app:
  local_port: 9191
  remote_port: 9191
